
import { Language } from "@/types";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import { useState } from "react";

interface TermsProps {
  language: Language;
}

const Terms = ({ language: initialLanguage }: TermsProps) => {
  const [language, setLanguage] = useState<Language>(initialLanguage);

  const handleLanguageChange = (newLanguage: Language) => {
    setLanguage(newLanguage);
  };

  return (
    <div className="flex flex-col min-h-screen bg-fortipass-soft-gray dark:bg-fortipass-charcoal">
      <Header language={language} onLanguageChange={handleLanguageChange} />
      <Navigation language={language} />
      
      <main className="flex-grow container mx-auto px-4 py-8 max-w-4xl">
        <h1 className="text-3xl font-bold mb-8 text-fortipass-charcoal dark:text-white">
          {language === "fr" ? "Conditions d'utilisation" : 
           language === "es" ? "Términos de uso" : 
           "Terms of Use"}
        </h1>
        
        <div className="space-y-6 text-gray-700 dark:text-gray-200">
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-fortipass-charcoal dark:text-white">
              {language === "fr" ? "Acceptation des conditions" : 
               language === "es" ? "Aceptación de términos" : 
               "Acceptance of Terms"}
            </h2>
            <p className="mb-4">
              {language === "fr" ? "En utilisant ce service, vous acceptez les présentes conditions d'utilisation. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser ce service." : 
               language === "es" ? "Al utilizar este servicio, acepta estos términos de uso. Si no está de acuerdo con estos términos, no utilice este servicio." : 
               "By using this service, you agree to these terms of use. If you do not agree to these terms, please do not use this service."}
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-fortipass-charcoal dark:text-white">
              {language === "fr" ? "Utilisation du service" : 
               language === "es" ? "Uso del servicio" : 
               "Use of Service"}
            </h2>
            <p className="mb-4">
              {language === "fr" ? "Vous vous engagez à utiliser ce service uniquement à des fins légales et conformément aux présentes conditions. Vous ne devez pas utiliser ce service d'une manière qui pourrait endommager, désactiver, surcharger ou altérer le service." : 
               language === "es" ? "Se compromete a utilizar este servicio solo con fines legales y de acuerdo con estos términos. No debe utilizar este servicio de una manera que pueda dañar, desactivar, sobrecargar o deteriorar el servicio." : 
               "You agree to use this service only for lawful purposes and in accordance with these terms. You must not use this service in any way that could damage, disable, overload, or impair the service."}
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-fortipass-charcoal dark:text-white">
              {language === "fr" ? "Confidentialité et sécurité" : 
               language === "es" ? "Privacidad y seguridad" : 
               "Privacy and Security"}
            </h2>
            <p className="mb-4">
              {language === "fr" ? "Nous prenons la protection de vos données au sérieux. Les mots de passe générés par ce service sont créés localement dans votre navigateur et ne sont pas stockés sur nos serveurs. Consultez notre politique de confidentialité pour plus d'informations." : 
               language === "es" ? "Nos tomamos en serio la protección de sus datos. Las contraseñas generadas por este servicio se crean localmente en su navegador y no se almacenan en nuestros servidores. Consulte nuestra política de privacidad para obtener más información." : 
               "We take the protection of your data seriously. Passwords generated by this service are created locally in your browser and are not stored on our servers. Please refer to our privacy policy for more information."}
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-fortipass-charcoal dark:text-white">
              {language === "fr" ? "Limitation de responsabilité" : 
               language === "es" ? "Limitación de responsabilidad" : 
               "Limitation of Liability"}
            </h2>
            <p className="mb-4">
              {language === "fr" ? "Dans toute la mesure permise par la loi applicable, nous ne serons pas responsables des dommages directs, indirects, accessoires, spéciaux, consécutifs ou exemplaires, y compris, mais sans s'y limiter, les pertes de données ou de profits, résultant de ou liés à votre utilisation du service." : 
               language === "es" ? "En la máxima medida permitida por la ley aplicable, no seremos responsables de daños directos, indirectos, incidentales, especiales, consecuentes o ejemplares, incluidos, entre otros, pérdidas de datos o ganancias, que surjan de o estén relacionados con su uso del servicio." : 
               "To the maximum extent permitted by applicable law, we will not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to, damages for loss of data or profits, arising out of or related to your use of the service."}
            </p>
          </div>
          
          <div>
            <h2 className="text-2xl font-semibold mb-4 text-fortipass-charcoal dark:text-white">
              {language === "fr" ? "Modifications des conditions" : 
               language === "es" ? "Cambios en los términos" : 
               "Changes to Terms"}
            </h2>
            <p className="mb-4">
              {language === "fr" ? "Nous nous réservons le droit de modifier ces conditions à tout moment. Votre utilisation continue du service après la publication des modifications constitue votre acceptation de ces modifications." : 
               language === "es" ? "Nos reservamos el derecho de modificar estos términos en cualquier momento. Su uso continuado del servicio después de la publicación de los cambios constituye su aceptación de dichos cambios." : 
               "We reserve the right to modify these terms at any time. Your continued use of the service after posting of the changes constitutes your acceptance of such changes."}
            </p>
          </div>
        </div>
      </main>
      
      <Footer language={language} />
    </div>
  );
};

export default Terms;
